set = "default"
generated = "2025-10-25T06:07:19.062Z"
count = 2

[[fragments]]
id = "0"
category = "INFO"
file = ".cms/default/0.md"
content = """Hello
"""
[[fragments.occurrences]]
file = "testbase/test.js"
line = 15
[[fragments.occurrences]]
file = "testbase/test.js"
line = 48
[[fragments.occurrences]]
file = "testbase/test.js"
line = 63
[[fragments.occurrences]]
file = "README.md"
line = 30
[[fragments.occurrences]]
file = "src/sidePanel.ts"
line = 131

[[fragments]]
id = "8923196433"
category = "INFO"
file = ".cms/default/8923196433.md"
content = """hello world"""
[[fragments.occurrences]]
file = "src/sidePanel.ts"
line = 117

